env: harvest

env_args:
  num_agents: 10
  render: False
  episode_limit: 100
  is_replay: False
  view_size: 15
  map: "default10"
  extra_args:
    random_spawn_point: False # spawn point & rotation
    random_spawn_rotation: 0 # None(empty): random, # 0:up, 1:down, 2:left, 3:right
    disable_rotation_action: True
    disable_fire_action: True
    obs_color: 'simplified' # full, simplified

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 5050000